# Generated by Django 5.0.2 on 2024-04-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_passenger_booking_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='photo',
            field=models.ImageField(db_column='photo', default=1, help_text='Photo', upload_to='travel/passengers', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
