# Generated by Django 5.0.2 on 2024-04-03 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_reservation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rating',
            field=models.DecimalField(db_column='rating', decimal_places=1, default=0, help_text='Travel rating (0.0 - 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
