# Generated by Django 5.0.2 on 2024-05-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_traveldestination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelimage',
            name='is_gallery_image',
            field=models.BooleanField(db_column='is_gallery_image', default=False, help_text='Is gallery image', verbose_name='Is gallery image'),
        ),
    ]
