# Generated by Django 5.0.2 on 2024-04-02 06:34

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import spectrum.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated at', null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Deleted at', null=True, verbose_name='Deleted at')),
                ('name', models.CharField(db_column='name', help_text='Name', max_length=255, unique=True, verbose_name='Name')),
                ('address', models.CharField(db_column='address', help_text='Address', max_length=255, verbose_name='Address')),
                ('email', models.EmailField(db_column='email', help_text='Email Address', max_length=255, verbose_name='Email Address')),
                ('mobile_phone', models.CharField(db_column='mobile_phone', help_text='Mobile Phone', max_length=255, verbose_name='Mobile Phone')),
                ('theme_color', spectrum.fields.ColorField(blank=True, db_column='theme_color', default='#fcccca', help_text='Theme Color', null=True, verbose_name='Theme Color')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Is Active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portals',
                'db_table': 'travel_portal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated at', null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Deleted at', null=True, verbose_name='Deleted at')),
                ('name', models.CharField(db_column='name', help_text='Name', max_length=255, verbose_name='Name')),
                ('highlight_feature', models.CharField(db_column='highlight_feature', help_text='Highlight Feature', max_length=25, verbose_name='Highlight Feature')),
                ('start_date', models.DateField(db_column='start_date', help_text='Start Date', verbose_name='Start Date')),
                ('end_date', models.DateField(db_column='end_date', help_text='End Date', verbose_name='End Date')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Is Active', verbose_name='Is Active')),
                ('all_inclusive', models.BooleanField(db_column='all_inclusive', default=False, help_text='All Inclusive', verbose_name='All Inclusive')),
                ('is_capacity_full', models.BooleanField(db_column='is_capacity_full', default=False, help_text='Is Capacity Full', verbose_name='Is Capacity Full')),
                ('cancelled', models.BooleanField(db_column='cancelled', default=False, help_text='Cancelled', verbose_name='Cancelled')),
                ('max_passengers', models.PositiveIntegerField(db_column='max_passengers', default=1, help_text='Max Passengers', verbose_name='Max Passengers')),
                ('description', models.TextField(db_column='description', help_text='Description', verbose_name='Description')),
                ('cover_image', models.ImageField(db_column='cover_image', help_text='Cover Image', upload_to='travel/travels', verbose_name='Cover Image')),
                ('inclusions', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, db_column='inclusions', help_text='Inclusions', size=10, verbose_name='Inclusions')),
                ('restrictions', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, db_column='restrictions', help_text='Restrictions', size=10, verbose_name='Restrictions')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
                'db_table': 'travel_travel',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated at', null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Deleted at', null=True, verbose_name='Deleted at')),
                ('first_name', models.CharField(db_column='first_name', help_text='First Name', max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='last_name', help_text='Last Name', max_length=250, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, db_column='phone', help_text='Phone', max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, db_column='email', help_text='Email Address', max_length=255, null=True, verbose_name='Email Address')),
                ('booking_confirmed', models.BooleanField(db_column='booking_confirmed', default=True, help_text='Booking Confirmed', verbose_name='Booking Confirmed')),
                ('travel', models.ForeignKey(db_column='travel_id', help_text='Travel', on_delete=django.db.models.deletion.CASCADE, related_name='travel_passengers', related_query_name='travel_passenger', to='travel.travel', verbose_name='Travel')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'db_table': 'travel_passenger',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated at', null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Deleted at', null=True, verbose_name='Deleted at')),
                ('name', models.CharField(db_column='name', help_text='Name', max_length=255, verbose_name='Name')),
                ('start_date', models.DateField(db_column='start_date', help_text='Start Date', verbose_name='Start Date')),
                ('end_date', models.CharField(db_column='end_date', help_text='End Date', verbose_name='End Date')),
                ('image', models.ImageField(db_column='image', help_text='Image', upload_to='travel/travel_destinations', verbose_name='Image')),
                ('travel', models.ForeignKey(db_column='travel_id', help_text='Travel', on_delete=django.db.models.deletion.CASCADE, related_name='travel_destinations', related_query_name='travel_destination', to='travel.travel', verbose_name='Travel')),
            ],
            options={
                'verbose_name': 'Travel Destination',
                'verbose_name_plural': 'Travel Destinations',
                'db_table': 'travel_travel_destination',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelImage',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated at', null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Deleted at', null=True, verbose_name='Deleted at')),
                ('image', models.ImageField(db_column='image', help_text='Image', upload_to='travel/travel_images', verbose_name='Image')),
                ('travel', models.ForeignKey(db_column='travel_id', help_text='Travel', on_delete=django.db.models.deletion.CASCADE, related_name='travel_images', related_query_name='travel_image', to='travel.travel', verbose_name='Travel')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
                'db_table': 'travel_travel_image',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated at', null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Deleted at', null=True, verbose_name='Deleted at')),
                ('name', models.CharField(db_column='name', help_text='Name', max_length=255, unique=True, verbose_name='Name')),
                ('url', models.CharField(db_column='url', help_text='Url of the social media account', max_length=255, verbose_name='URL')),
                ('description', models.TextField(blank=True, db_column='description', help_text='Description', verbose_name='Description')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Is Active', verbose_name='Is Active')),
                ('portal', models.ForeignKey(db_column='portal_id', help_text='Portal', on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', related_query_name='social_media_account', to='travel.portal', verbose_name='Portal')),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': 'Social Media Accounts',
                'db_table': 'travel_social_media_account',
                'ordering': ['name'],
                'unique_together': {('name', 'portal')},
            },
        ),
    ]
