# Generated by Django 5.0.2 on 2024-04-02 06:39

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_travel_inclusions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='restrictions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, db_column='restrictions', default=list, help_text='Restrictions', size=10, verbose_name='Restrictions'),
        ),
    ]
