# Generated by Django 5.0.2 on 2024-04-03 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_travel_restrictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='booking_confirmed',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='travel',
        ),
        migrations.AlterField(
            model_name='travel',
            name='highlight_feature',
            field=models.CharField(blank=True, db_column='highlight_feature', help_text='Highlight Feature', max_length=25, verbose_name='Highlight Feature'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, help_text='Created at', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='Updated at', null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', help_text='Deleted at', null=True, verbose_name='Deleted at')),
                ('review', models.TextField(blank=True, db_column='review', help_text='Review', verbose_name='Review')),
                ('booking_confirmed', models.BooleanField(db_column='booking_confirmed', default=False, help_text='Booking Confirmed', verbose_name='Booking Confirmed')),
                ('passenger', models.ForeignKey(db_column='passenger_id', help_text='Passenger', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_passengers', related_query_name='reservation_passenger', to='travel.passenger', verbose_name='Passenger')),
                ('travel', models.ForeignKey(db_column='travel_id', help_text='Travel', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_travels', related_query_name='reservation_travel', to='travel.travel', verbose_name='Travel')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'travel_reservation',
            },
        ),
    ]
