# Generated by Django 5.0.2 on 2024-04-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_passenger_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rating',
            field=models.DecimalField(db_column='rating', decimal_places=1, default=0, help_text='Travel rating (0.0 - 5.0)', max_digits=3, verbose_name='Rating'),
        ),
    ]
