# Generated by Django 5.0.2 on 2024-04-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldestination',
            name='end_date',
            field=models.DateField(db_column='end_date', help_text='End Date', verbose_name='End Date'),
        ),
    ]
