# Generated by Django 5.0.2 on 2024-04-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_traveldestination_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldestination',
            name='description',
            field=models.TextField(blank=True, db_column='description', help_text='Description', verbose_name='Description'),
        ),
    ]
