# Generated by Django 5.0.2 on 2024-05-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_travelimage_is_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='url',
            field=models.CharField(blank=True, db_column='url', help_text='URL of the travel images', max_length=255, null=True, verbose_name='URL'),
        ),
    ]
